steps:
        
  - name: maven:3.3-jdk-8
    entrypoint: mvn
    args: ['--version']    
  - name: maven:3.3-jdk-8
    entrypoint: mvn
    args: ['test']
  - name: maven:3.3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
 - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/java-373610/hello-world:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/java-373610/hello-world:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta','run', 'deploy', 'hello-world', '--region=asia-east1', '--port=8080', '--platform=managed', '--image=gcr.io/java-373610/hello-world:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: 
      - run
      - --filename=deployment.yaml
      ##- --image=gcr.io/$PROJECT-ID/demo-app
      - --location=asia-east1-a
      - --cluster=cluster-1

  
 

