steps:  
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh medium-server --zone=asia-east1-a --command='/bin/bash /home/akshpawar2056/java/hello-world-java'

