steps:  
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh akshpawar2056@cloudshell-server --zone=asia-east1-a --command='/bin/bash /'

