steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/java-373610/hello-world:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/java-373610/hello-world:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta','run', 'deploy', 'hello-world', '--region=asia-east1', '--port=8080', '--platform=managed', '--image=gcr.io/java-373610/hello-world:$COMMIT_SHA']

